### ISSUE TITLE
ryzen 7 5700u tambem funcionaria?

### ISSUE THREAD

**Issue by MullerHub** [luchina-gabriel/EFI-AFOX-B450M-Ryzen-7-5700G-APU-PUBLIC#1]
ryzen 7 5700u tambem funcionaria? ou a adaptação seria pequena?
Vou testar agora e ver o que acontece, daqui a pouco passo meu feedback

**Comment by luchina-gabriel** [comment]
Recomendo assistir a live, pois com certeza a EFI será diferente.
https://youtu.be/d9-NDswXwBo

**Comment by MullerHub** [comment]
Assisti e fiz tudo certinho, porem estou com erro de bluetoothd (209)

![WhatsApp Image 2023-09-23 at 22 19 27](https://github.com/luchina-gabriel/EFI-AFOX-B450M-Ryzen-7-5700G-APU-PUBLIC/assets/105472842/f2a12009-23c4-4fbe-841a-034e17455c77)

**Comment by luchina-gabriel** [comment]
Este erro aconteceu na live, não lembro o que fiz, mas aconteceu na live e concertamos rsrs

**Comment by MullerHub** [comment]
Obrigado, vi a live 4x e consegui hahaha, agora to com problema em tirar o boot do pendrive pro NVME sksksks
